<?php
/**
 * @file
 * Contains implementing some hooks.
 */

/**
 * Implements hook_cron().
 */
function openweathermap_cron() {
    // We access our service for getting weather from OpenWeatherMap web service.
    $service = \Drupal::service('openweathermap.weather_service');
    
    $service->getWeather5Days();    
    $service->getCurrentWeather();
}

/**
 * Implements hook_theme().
 */
function openweathermap_theme() {
    $items = [
        'weather_map' => [
            'render element' => 'element',
        ],
        'weather_tile_map' => [
            'render element' => 'element',
        ],
    ];
    return $items;
}